'use client';

export default function ReportModal({ result, onClose }) {
  if (!result) return null;
  const r = result;
  const auth = r.authentication;

  return (
    <div className="modal-overlay" onClick={(e) => e.target.classList.contains('modal-overlay') && onClose()}>
      <div className="modal">
        <div className="modal-head">
          <h2>&#128203; Forensic Incident Report</h2>
          <button className="modal-close" onClick={onClose}>&times;</button>
        </div>
        <div className="modal-body">
          <h3>Incident Summary</h3>
          <div className="rline"><span>Investigation ID</span><span>{r.investigation_id}</span></div>
          <div className="rline"><span>Classification</span><span style={{ color: 'var(--red)', fontWeight: 700 }}>{r.risk.classification}</span></div>
          <div className="rline"><span>Threat Score</span><span style={{ color: 'var(--red)', fontWeight: 700 }}>{r.risk.score} / 100</span></div>
          <div className="rline"><span>Sender</span><span>{r.parsed.from_addr}</span></div>
          <div className="rline"><span>Recipient</span><span>{(r.parsed.to_list || []).join(', ')}</span></div>
          <div className="rline"><span>Subject</span><span>{r.parsed.subject}</span></div>

          <h3>Authentication</h3>
          <div className="rline"><span>SPF</span><span>{(auth.spf || '').toUpperCase()}</span></div>
          <div className="rline"><span>DKIM</span><span>{(auth.dkim || '').toUpperCase()}</span></div>
          <div className="rline"><span>DMARC</span><span>{(auth.dmarc || '').toUpperCase()}</span></div>

          <h3>Detection Findings</h3>
          {r.risk.reasons.map((reason, i) => (
            <div className="rline" key={i}><span>&#10003; {reason.text}</span><span>+{reason.weight}</span></div>
          ))}

          <h3>Indicators of Compromise</h3>
          {r.iocs.map((ioc, i) => (
            <div className="rline" key={i}><span>{ioc.type.toUpperCase()}</span><span>{ioc.value}</span></div>
          ))}

          <div className="disclaimer" style={{ marginTop: 20 }}>
            This report was generated by a transparent rule-based detection engine for the SIH presentation (PS-26106).
          </div>
        </div>
        <div className="modal-foot">
          <button className="btn ghost" onClick={onClose}>Close</button>
          <button className="btn primary" onClick={() => window.print()}>&#8615; Print / Save PDF</button>
        </div>
      </div>
    </div>
  );
}
